### ISSUE TITLE
Error: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by hlinero** [probablykasper/readme-template#1]
When running the WF I keep getting an error in the step **Generate README.md**: 

```
Run probablykasper/readme-template-action@v1
template: TEMPLATE.md
output: README.md
User data
    - Fetching
    - Injecting
TypeError: Cannot read property 'split' of undefined
    at inject (/home/runner/work/_actions/probablykasper/readme-template-action/v1/dist/index.js:10961:15)
    at run (/home/runner/work/_actions/probablykasper/readme-template-action/v1/dist/index.js:10996:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Cannot read property 'split' of undefined
```

My wf.yml file is the same as the one you posted in your repo README file:

```yml
name: Readme Template Generator
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: probablykasper/readme-template-action@v1
        with:
          token: ${{ secrets.README_TEMPLATE_TOKEN }}
          template: TEMPLATE.md
          output: README.md
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add .
            git commit -m "Auto-update README.md"
            git push
          fi

```

The only difference is that I will execute this WF manually instead of it being scheduled. What can I do to solve this issue?

Thank you
